version: 2
jobs:
  build:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: Install build tools
          command: sudo apt-get update && sudo apt-get install build-essential cpio squashfs-tools debootstrap realpath
      - run:
          name: Import gpg key
          command: gpg --import building/apt-branch-config/default-key.asc
      - run:
          name: Pull down upstream dependencies
          command: building/pull-upstream.sh $CIRCLE_BRANCH || building/pull-upstream.sh master
      - run:
          name: Construct build chroot
          command: HOMEWORLD_CHROOT="$HOME/autobuild-chroot" USER="circleci" ./create-chroot.sh
      - run:
          name: Verify upstream dependencies
          command: echo "make -C upstream-check/ -j2 verify && killall gpg-agent" | HOMEWORLD_CHROOT="$HOME/autobuild-chroot" USER="circleci" ./enter-chroot-ci.sh
      - run:
          name: Launch build with glass
          command: cp building/apt-branch-config/branches-ci.yaml building/apt-branch-config/branches.yaml && echo "glass components -b root/master" | HOMEWORLD_CHROOT="$HOME/autobuild-chroot" USER="circleci" ./enter-chroot-ci.sh
          no_output_timeout: 3600
      - run:
          name: Display resulting binaries
          command: find building/binaries
